### PR TITLE
CORS: allowed methods config

### LINKED ISSUE #21: Abstract out allowed HTTP methods into DI config
Currently the list of allowed HTTP methods is hardcoded in the `RouteLoader`. However, as noted by #20, the list is duplicated in the `CorsServiceProvider`.

If the method list was defined in DI config and injected into both classes, it would not only remove the duplicated definitions but would also allow people to customise the list to their own ends.

### PR DESCRIPTION
**Pull request by downsider**
Fixes #21 
Add ability to configure the HTTP methods that can be used with a Lazy-Boy API

### CODE REVIEW

**Comment by downsider** [comment]
Actually, hold off on this.
The methods don't get injected into the route loader atm. I need to think how this should be done.

**Comment by downsider** [comment]
Issues addressed

**Comment by Dolondro** [comment]
I'm more skeptical about this one because it's a BC, current things using the CorsProvider will fail as their default config won't contain the get/post etc

**Comment by downsider** [comment]
The BC break is in the RouteLoader, adding the required arg `$allowedMethods` before the `$loaders` arg. If the DI config is not updated, the app will fail on any request due to the RouteLoader not having any loaders available. That is something that would show immediately up in development or testing.

Also, CORS wouldn't silently fail due to having no allowed methods. It too relies on the `router.allowedMethods` parameter, and would throw an exception if it didn't exist.

I agree that this is a breaking change. However it can be mitigated by adding release notes showing how to upgrade (I can provide these if necessary)

**Pull request closed without merging**
